version: '3.1'

services:
  pirawash-back:
    build:
      context: ./BACK
    image: mcr.microsoft.com/dotnet/samples:aspnetapp
    container_name: pirawash_back
    restart: always
    ports:
      - 6322:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
  pirawash-front:
    build:
      context: ./FRONT
    container_name: pirawash_front
    restart: always
    ports:
      - 6321:80
